apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-demo-image-classification
data:
  image_classification.py: |
{{ .Files.Get "model/image_prediction.py" | indent 4 }}
  result.html: |
{{ .Files.Get "model/templates/result.html" | indent 4 }}
